package com.didate.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategorycomboAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorycomboAllPropertiesEquals(Categorycombo expected, Categorycombo actual) {
        assertCategorycomboAutoGeneratedPropertiesEquals(expected, actual);
        assertCategorycomboAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorycomboAllUpdatablePropertiesEquals(Categorycombo expected, Categorycombo actual) {
        assertCategorycomboUpdatableFieldsEquals(expected, actual);
        assertCategorycomboUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorycomboAutoGeneratedPropertiesEquals(Categorycombo expected, Categorycombo actual) {
        assertThat(expected)
            .as("Verify Categorycombo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorycomboUpdatableFieldsEquals(Categorycombo expected, Categorycombo actual) {
        assertThat(expected)
            .as("Verify Categorycombo relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategorycomboUpdatableRelationshipsEquals(Categorycombo expected, Categorycombo actual) {}
}
