package com.didate.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndicatortypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicatortypeAllPropertiesEquals(Indicatortype expected, Indicatortype actual) {
        assertIndicatortypeAutoGeneratedPropertiesEquals(expected, actual);
        assertIndicatortypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicatortypeAllUpdatablePropertiesEquals(Indicatortype expected, Indicatortype actual) {
        assertIndicatortypeUpdatableFieldsEquals(expected, actual);
        assertIndicatortypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicatortypeAutoGeneratedPropertiesEquals(Indicatortype expected, Indicatortype actual) {
        assertThat(expected)
            .as("Verify Indicatortype auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicatortypeUpdatableFieldsEquals(Indicatortype expected, Indicatortype actual) {
        assertThat(expected)
            .as("Verify Indicatortype relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicatortypeUpdatableRelationshipsEquals(Indicatortype expected, Indicatortype actual) {}
}
