package com.didate.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OptionsetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsetAllPropertiesEquals(Optionset expected, Optionset actual) {
        assertOptionsetAutoGeneratedPropertiesEquals(expected, actual);
        assertOptionsetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsetAllUpdatablePropertiesEquals(Optionset expected, Optionset actual) {
        assertOptionsetUpdatableFieldsEquals(expected, actual);
        assertOptionsetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsetAutoGeneratedPropertiesEquals(Optionset expected, Optionset actual) {
        assertThat(expected)
            .as("Verify Optionset auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsetUpdatableFieldsEquals(Optionset expected, Optionset actual) {
        assertThat(expected)
            .as("Verify Optionset relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOptionsetUpdatableRelationshipsEquals(Optionset expected, Optionset actual) {}
}
