import { IProject } from 'app/entities/project/project.model';
import { IDHISUser } from 'app/entities/dhis-user/dhis-user.model';
import { ICategorycombo } from 'app/entities/categorycombo/categorycombo.model';
import { ITrackedEntityAttribute } from 'app/entities/tracked-entity-attribute/tracked-entity-attribute.model';
import { IOrganisationUnit } from 'app/entities/organisation-unit/organisation-unit.model';
import { IProgramIndicator } from 'app/entities/program-indicator/program-indicator.model';
import { IProgramStage } from 'app/entities/program-stage/program-stage.model';
import { TypeTrack } from 'app/entities/enumerations/type-track.model';

export interface IProgram {
  id: string;
  name?: string | null;
  created?: string | null;
  lastUpdated?: string | null;
  shortName?: string | null;
  description?: string | null;
  version?: number | null;
  enrollmentDateLabel?: string | null;
  incidentDateLabel?: string | null;
  programType?: string | null;
  displayIncidentDate?: boolean | null;
  ignoreOverdueEvents?: boolean | null;
  userRoles?: string | null;
  onlyEnrollOnce?: boolean | null;
  notificationTemplates?: string | null;
  selectEnrollmentDatesInFuture?: boolean | null;
  selectIncidentDatesInFuture?: boolean | null;
  trackedEntityType?: string | null;
  style?: string | null;
  skipOffline?: boolean | null;
  displayFrontPageList?: boolean | null;
  useFirstStageDuringRegistration?: boolean | null;
  expiryDays?: number | null;
  completeEventsExpiryDays?: number | null;
  openDaysAfterCoEndDate?: number | null;
  minAttributesRequiredToSearch?: number | null;
  maxTeiCountToReturn?: number | null;
  accessLevel?: string | null;
  displayEnrollmentDateLabel?: string | null;
  displayIncidentDateLabel?: string | null;
  registration?: boolean | null;
  withoutRegistration?: boolean | null;
  displayShortName?: string | null;
  displayDescription?: string | null;
  displayFormName?: string | null;
  displayName?: string | null;
  organisationUnitsCount?: number | null;
  programStagesCount?: number | null;
  programIndicatorsCount?: number | null;
  programTrackedEntityAttributesCount?: number | null;
  organisationUnitsContent?: string | null;
  programStagesContent?: string | null;
  programIndicatorsContent?: string | null;
  programTrackedEntityAttributesContent?: string | null;
  track?: keyof typeof TypeTrack | null;
  project?: IProject | null;
  createdBy?: IDHISUser | null;
  lastUpdatedBy?: IDHISUser | null;
  categoryCombo?: ICategorycombo | null;
  programTrackedEntityAttributes?: ITrackedEntityAttribute[] | null;
  organisationUnits?: IOrganisationUnit[] | null;
  programIndicators?: IProgramIndicator[] | null;
  programStages?: IProgramStage[] | null;
}

export type NewProgram = Omit<IProgram, 'id'> & { id: null };
